### ISSUE TITLE
explain what  business unit means

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/kpi-data-dashboard#18]
>I wasn’t sure what business unit meant in the contact info. 
(submitted by volunteer tester)

**Comment by haileypate** [comment]
@wrays ?

**Comment by wrays** [comment]
FDU = Fund-Dept-Unit
Example = 1000-9100-8840
Where 1000 = General Fund
            9100 = Code for HHSD
            8840 = Code for Health IT

I work in Health IT which is my Business Unit with the Health and Human Services Department.

**Comment by wrays** [comment]
Every dataset emerges from within an FDU
Every performance measure is tied to an FDU
Budgets are aligned with FDUs

**Comment by haileypate** [comment]
okay.. cool! do you have any suggestions for how we should explain this in the survey? Or should I just copy in some of this...

**Comment by wrays** [comment]
"Business unit" refers to the smallest organizational unit within the City's structure. Typically, a department may have a division, within that a program, and within that a business unit. It is the group within which you work.

**Comment by haileypate** [comment]
we added language on the survey to address this
